### PR TITLE
added previous answer feature

### LINKED ISSUE #5: Add an "Ans" Button in this calculator.
Create an "Ans" button to use previous answer in calculation.

### PR DESCRIPTION
**Pull request by Virtual4087**
Fixes #5

### CODE REVIEW

**Comment by Virtual4087** [comment]
Check it out

**Comment by Surajit0573** [comment]
> Check it out

Don't raise PR until you get assigned. I am assigning you. 
This PR has a little problem. When the Display is not clear and the "Ans" button is clicked, it automatically doubles the answer which is not intended.

**Comment by Virtual4087** [comment]
ok i'm on it

**Comment by Virtual4087** [comment]
instead of adding the value of ans in the display should i just concatenate the ans with the display value like a string?

**Comment by Surajit0573** [comment]
> instead of adding the value of ans in the display should i just concatenate the ans with the display value like a string?

figure it out.

**Pull request closed without merging**
