### PR TITLE
added functions

### PR DESCRIPTION
**Pull request by gurjott**
added the function of log, power and square root

### CODE REVIEW

**Comment by Surajit0573** [comment]
@gurjott square root and log buttons have some problems, fix them.

**Comment by gurjott** [comment]
@Surajit0573 first input the number then press any of the button "log" or "sqrt" then press equals, it will work

**Comment by Surajit0573** [comment]
> @Surajit0573 first input the number then press any of the button "log" or "sqrt" then press equals, it will work

7+log(5)....this log button can't do it in one go.
Don't take the whole display value just take it till any operator appears.

**Comment by Surajit0573** [comment]
@gurjott And your branch has some conflicts....try to sync fork -> pull -> then work on it.

**Pull request closed without merging**
