### PR TITLE
ADD MORE BUTTONS

### PR DESCRIPTION
**Pull request by ZainabR11**
**Pull Request Description**

This pull request introduces new mathematical functions to the calculator, enhancing its functionality. The following buttons have been added:

- **Power (^)**: Calculates a number raised to a specified power.
- **Modulo (%)**: Computes the remainder of a division operation.
- **Square Root (√)**: Finds the square root of a number.
- **Logarithm (log)**: Calculates the logarithm of a number.
- and more options.

These additions allow users to perform a broader range of mathematical operations with ease. The JavaScript functions for these operations are included, and the buttons are integrated into the calculator's interface.

Please review this pull request, and feel free to provide feedback or suggestions for further enhancements. Your input is highly valued!

Add new Buttons #8

https://github.com/Surajit0573/Calculator/assets/122125525/fdd1f5c3-a06e-4613-84c0-5f511d1f25df

### CODE REVIEW

**Comment by ZainabR11** [comment]
If you like this pull request , please merge for hacktoberfest 2023.

**Comment by Surajit0573** [comment]
This modulo button gives a percentage, and the power button gives only a square. Fix this. Remove sin, cos, and tan buttons. Keep the "ans" button, you remove that to resolve the conflict, I think.

**Comment by ZainabR11** [comment]
That is not the module button, that is the percentage button, and for the power it is just for the square. Kindly specify how many buttons you want and what types of functions/buttons you want. Give detail. Zainab Rizwan-------- Original message --------From: SURAJIT MAITY ***@***.***>Date: Thu, 12 Oct 2023, 10:09 amTo: Surajit0573/Calculator ***@***.***>Cc: ZainabR11 ***@***.***>, Author ***@***.***>Subject: Re: [Surajit0573/Calculator] ADD MORE BUTTONS (PR #14)
This modulo button gives a percentage, and the power button gives only a square. Fix this. Remove sin, cos, and tan buttons. Keep the "ans" button, you remove that to resolve the conflict, I think.

**Comment by Surajit0573** [comment]
> **Pull Request Description**
> 
> This pull request introduces new mathematical functions to the calculator, enhancing its functionality. The following buttons have been added:
> 
> * **Power (^)**: Calculates a number raised to a specified power.
> * **Modulo (%)**: Computes the remainder of a division operation.
> * **Square Root (√)**: Finds the square root of a number.
> * **Logarithm (log)**: Calculates the logarithm of a number.


Read Your own Pull Request Description.

**Comment by ZainabR11** [comment]
I apologize for what I mentioned, I am first time contributing for Hacktoberfest 2023.Kindly give details on how many buttons you want and what operation you want them to perform. Thank youZainab Rizwan-------- Original message --------From: SURAJIT MAITY ***@***.***>Date: Thu, 12 Oct 2023, 10:29 amTo: Surajit0573/Calculator ***@***.***>Cc: ZainabR11 ***@***.***>, Author ***@***.***>Subject: Re: [Surajit0573/Calculator] ADD MORE BUTTONS (PR #14)

Pull Request Description
This pull request introduces new mathematical functions to the calculator, enhancing its functionality. The following buttons have been added:
Power (^): Calculates a number raised to a specified power.Modulo (%): Computes the remainder of a division operation.Square Root (√): Finds the square root of a number.Logarithm (log): Calculates the logarithm of a number.

Read Your own Pull Request Description.

**Comment by Surajit0573** [comment]
So, first sync fork and pull to remove any conflicts, then add these 4 buttons (must) ...

Power (^): Calculates a number raised to a specified power. (ex :- 2^3 = 8)
Modulo (%): Computes the remainder of a division operation. (ex:- 15%4 = 3)
Square Root (√): Finds the square root of a number.  (ex:- √25 = 5)
Logarithm (log): Calculates the logarithm of a number. (ex:- log 10  = 1)

And you can keep the "CE" and "x!" buttons as you already made them, and they are working fine.

**Comment by ZainabR11** [comment]
Okay, will do these changes. Zainab Rizwan-------- Original message --------From: SURAJIT MAITY ***@***.***>Date: Thu, 12 Oct 2023, 10:50 amTo: Surajit0573/Calculator ***@***.***>Cc: ZainabR11 ***@***.***>, Author ***@***.***>Subject: Re: [Surajit0573/Calculator] ADD MORE BUTTONS (PR #14)
So, first sync fork and pull to remove any conflicts, then add these 4 buttons (must) ...
Power (^): Calculates a number raised to a specified power. (ex :- 2^3 = 8)
Modulo (%): Computes the remainder of a division operation. (ex:- 15%4 = 3)
Square Root (√): Finds the square root of a number.  (ex:- √25 = 5)
Logarithm (log): Calculates the logarithm of a number. (ex:- log 10  = 1)
And you can keep the "CE" and "x!" buttons as you already made them, and they are working fine.

**Comment by ZainabR11** [comment]
One more question about power,  do you want cube or square or any power? Do I have to remove sin, cos, tan? Should I keep the Ans button? Zainab Rizwan-------- Original message --------From: SURAJIT MAITY ***@***.***>Date: Thu, 12 Oct 2023, 10:50 amTo: Surajit0573/Calculator ***@***.***>Cc: ZainabR11 ***@***.***>, Author ***@***.***>Subject: Re: [Surajit0573/Calculator] ADD MORE BUTTONS (PR #14)
So, first sync fork and pull to remove any conflicts, then add these 4 buttons (must) ...
Power (^): Calculates a number raised to a specified power. (ex :- 2^3 = 8)
Modulo (%): Computes the remainder of a division operation. (ex:- 15%4 = 3)
Square Root (√): Finds the square root of a number.  (ex:- √25 = 5)
Logarithm (log): Calculates the logarithm of a number. (ex:- log 10  = 1)
And you can keep the "CE" and "x!" buttons as you already made them, and they are working fine.

**Comment by Surajit0573** [comment]
any power | yes | yes

**Comment by Surajit0573** [comment]
@ZainabR11  and don't reply from email directly it looks weird, use github.

**Comment by ZainabR11** [comment]
OkayZainab Rizwan-------- Original message --------From: SURAJIT MAITY ***@***.***>Date: Thu, 12 Oct 2023, 11:01 amTo: Surajit0573/Calculator ***@***.***>Cc: ZainabR11 ***@***.***>, Mention ***@***.***>Subject: Re: [Surajit0573/Calculator] ADD MORE BUTTONS (PR #14)
@ZainabR11  and don't reply from email directly it looks weird.

**Comment by ZainabR11** [comment]
Is this PR merged? @Surajit0573

**Comment by ZainabR11** [comment]
I have made changes as you described me. But Ans button is not working. So is it mandatory to add this button? @Surajit0573

**Comment by ZainabR11** [comment]
https://github.com/Surajit0573/Calculator/assets/122125525/9bcb0d80-0558-4f29-848f-9e620c6c22d8

Is this demo video satisfactory or you want some other changes here?

**Comment by ZainabR11** [comment]
@Surajit0573

**Comment by Surajit0573** [comment]
Looks good, push it.

**Comment by ZainabR11** [comment]
Thankyou, I  am facing problem in 'Ans' as its not working, so is it mandatory to add this button? Or I just push the file non-working 'Ans' button?

**Comment by ZainabR11** [comment]
@Surajit0573

**Comment by Surajit0573** [comment]
Just push it, and **No** need to resolve any conflict (if any).

**Comment by Surajit0573** [comment]
@ZainabR11 is there any problem !?

**Comment by ZainabR11** [comment]
I sincerely apologize for the delayed response, and I appreciate your understanding. Due to some reasons , I was not able to respond.

I assure you that I will push it till Monday.

Your patience is greatly appreciated, and I am thankful for your understanding. 

Thank you for your time and consideration. @Surajit0573

**Pull request closed without merging**
